### ISSUE TITLE
Allow users to download Raven-like csv format of annotations

### ISSUE THREAD

**Issue by JacobGlennAyers** [UCSD-E4E/Pyrenote#139]
- Start by writing a .py file that takes in the Kaleidoscope-like format that we are currently working with, and converts it into the Raven-like format.
- This is something that would be very helpful for groups such as Kitzes lab that use Raven in their workflow.

**Comment by JacobGlennAyers** [comment]
Example of raven-based annotations - 
OpenSoundscape Reference: http://opensoundscape.org/en/latest/tutorials/raven.html
In our google drive: https://drive.google.com/drive/folders/102sXMqzTYV4s3B1JRJvT1vskj_uwYybQ

**Comment by Sean1572** [comment]
Frist pass in `raven-annotations` branch

**Comment by Sean1572** [comment]
`Selection,View,Begin Time (s),End Time (s),Low Freq (Hz),High Freq (Hz),Species
=========================
Lipaugus-vociferans-540.wav
 ========================= 
1,Spectrogram 1,1,2.9597,4.8395,100.0,200000.0,NO LABEL
1,Spectrogram 1,1,0.6099,2.1498,100.0,200000.0,NO LABEL
=========================
Lipaugus-vociferans-540.wav
 ========================= `

Current output (this project had two of the same file)

**Comment by Sean1572** [comment]
Tried to closer match ouput found at http://opensoundscape.org/en/latest/tutorials/raven.html

**Comment by Sean1572** [comment]
still got some work but getting closer to being useful

**Comment by Sean1572** [comment]
Can't actually work on raven, will debug this later

**Comment by Sean1572** [comment]
So I got raven annotations to work. Turns out they were tab delimited and that was my issue.  The thing is the text file cannot be uploaded directly to raven. Instead the user will need to copy the text to a diffrent file to upload since the applications focuses on only one audio clip at a time
![image](https://user-images.githubusercontent.com/25123131/129428015-f00c4c47-3828-4758-bfdf-edffcca5a37f.png)
Look at the end bit not too bad tho

I'm sure at this point we can ignore that. This is the best system we have thusfar
