### ISSUE TITLE
Password recovery idea

### ISSUE THREAD

**Issue by Sean1572** [UCSD-E4E/Pyrenote#36]
Create systems for admins and or users to recover lost passwords

**Comment by JacobGlennAyers** [comment]
I believe the importance of this depends on how high of a priority we place on tracking the users. Because if we decide that we don't care, then we can just have them create a new account in case they forget. If we decide that it is pretty important to track users, then we should at least allow the admins to solve problems (seems easier than a whole password forgetting email system)

**Comment by Sean1572** [comment]
Seeing as it has been nearly a few months with this idea, I decided to leave it for now. Once the project scales up I'll worry about this system but for now it is just taking up space
